django-dotman007_richardscrumy/dotman007_richardscrumy/urls.py
from django.urls import path
from django.urls import path
from . import views



urlpatterns = [
    path('', views.index, name='index')
]

dotman007_richardscrumy/urls.py
from django.urls import path, include
from . import views

app_name = "dotman007_richardscrumy"

urlpatterns = [
    # Lab 21
    path('register/', views.signUp, name='register'),
    path('login_page/', views.loginPage, name='login_page'),
    path('logout_page/', views.logoutUser, name='logout_page'),
    path('group/', views.change_group, name='group'),

    
    path('', views.index, name="about"),
    path('goal/', views.goal, name='goal'),
    path('success/', views.success, name='success'),
    path('move_goal/<int:goal_id>/', views.move_goal, name="move_goal"),

    # url path lab 13
    path('addgoal/', views.add_goal, name="add_goal"),

    path('home/', views.home, name="home"),

    # lab 17
    path('accounts/', include('django.contrib.auth.urls'))
]

myscrumy/urls.py
from django.contrib import admin
from django.urls import path, include
from dotman007_richardscrumy import urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('dotman007_richardscrumy/', include('dotman007_richardscrumy.urls', namespace="dotman007_richardscrumy")),
]

django-dotman007_richardscrumy/dotman007_richardscrumy/models.py
from django.db import models

# Create your models here.

dotman007_richardscrumy/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import fields
from django.forms import ModelForm



# Create your models here.

class GoalStatus(models.Model):
    status_name=models.CharField(max_length=300)

    def __str__(self):
        return self.status_name


class ScrumyGoals(models.Model):
    goal_name=models.CharField(max_length=100)
    goal_id = models.IntegerField()
    created_by = models.CharField(max_length=100)
    moved_by = models.CharField(max_length=100)
    owner=models.CharField(max_length=50)
    goal_status=models.ForeignKey(GoalStatus, on_delete=models.PROTECT)
    user=models.ForeignKey(User, on_delete=models.CASCADE, related_name='louis')

    def __str__(self):
        return self.goal_name

    


class ScrumyHistory(models.Model):
    moved_by=models.CharField(max_length=100)
    created_by=models.CharField(max_length=50)
    moved_from=models.CharField(max_length=50)
    moved_to=models.CharField(max_length=50)
    time_of_action=models.DateTimeField()
    goal=models.ForeignKey(ScrumyGoals, on_delete=models.PROTECT)

    def __str__(self):
        return self.created_by
    
class SignupForm(ModelForm):
    class Meta:
        model= User
        fields =['first_name', 'last_name', 'email', 'username', 'password']


class CreateGoalForm(ModelForm):
    class Meta:
        model= ScrumyGoals
        fields= ['goal_name', 'user',]

dotman007_richardscrumy/forms.py
from django.contrib.auth import models
from django.forms import ModelForm, fields
from .models import ScrumyGoals, GoalStatus, ScrumyHistory

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User, Group
from django import forms


class SignupForm(UserCreationForm):
    class Meta:
        model= User
        fields =['first_name', 'last_name', 'email', 'username', 'password1', 'password2' ]


class CreateGoalForm(ModelForm):
    class Meta:
        model= ScrumyGoals
        fields= ['goal_name',]

class MoveGoalForm(ModelForm):
    class Meta:
        model= ScrumyGoals
        fields=['goal_status',]

class GroupChange(forms.Form):
    group_name = forms.CharField(label='Group name', max_length=100)

django-dotman007_richardscrumy/dotman007_richardscrumy/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.

def index(request):
    return HttpResponse("Welcome to Django") 

dotman007_richardscrumy/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import SignupForm, CreateGoalForm, MoveGoalForm, GroupChange
from .models import ScrumyGoals, GoalStatus, ScrumyHistory
from django.contrib.auth.models import User, Group
import random
from django.contrib import messages

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required


# Create your views here.

# this is the registeration view
def index(request):
    form= SignupForm()
    
    if request.method =='POST':
        form= SignupForm(request.POST)
    
        if form.is_valid():
            user = form.save()

            group = Group.objects.get(name='Developer')
            user.groups.add(group)

            user= form.cleaned_data.get('username')
            messages.success(request, 'Account successfully created for '+ user)

            return redirect('dotman007_richardscrumy:login_page')
        else:
            form= SignupForm()

    context={'form': form}
    return render(request, 'dotman007_richardscrumy/index.html', context) 


# My Lab 21 task
def signUp(request):
    form = SignupForm()

    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user=form.save()

            group = Group.objects.get(name='Developer')
            user.groups.add(group)

            return redirect('dotman007_richardscrumy:login_page')

    context={'form':form}
    return render(request, 'dotman007_richardscrumy/register.html', context)

# this is the loginPage view for lab 21
def loginPage(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('dotman007_richardscrumy:home')
        else:
            messages.info(request, 'Username OR Password is not Correct')

    context = {}
    return render(request, 'dotman007_richardscrumy/login_page.html', context)

def logoutUser(request):
    logout(request)
    return redirect('dotman007_richardscrumy:login_page')



def goal(request):
    goal = ScrumyGoals.objects.get(goal_name='Learn Django')

    return HttpResponse(goal)


def success(request):
    
    return render(request, 'dotman007_richardscrumy/success.html')


@login_required(login_url='dotman007_richardscrumy:login_page')
def move_goal(request, goal_id):

    try: 
        obj = ScrumyGoals.objects.get(goal_id=goal_id) 
    except Exception as e: 
        return render(
            request, 
            'dotman007_richardscrumy/exception.html', 
            {'error': 'A record with that goal id does not exist'}
        )
    else: 
        if request.method == 'POST':
            form = MoveGoalForm(request.POST)
            d_group = False
            q_group = False
            a_group = False
            o_group = False
            role_name =""  
            if form.is_valid():
                myGoalStatus = GoalStatus.objects.get(status_name = form.cleaned_data['goal_status'])
                weeklyGoalStatus = GoalStatus.objects.get(status_name = 'Weekly Goal')
                dailyGoalStatus = GoalStatus.objects.get(status_name = 'Daily Goal')
                verifyGoalStatus = GoalStatus.objects.get(status_name = 'Verify Goal')
                doneGoalStatus = GoalStatus.objects.get(status_name = 'Done Goal')

                forms = form.cleaned_data['goal_status']

                if (request.user.groups.filter(name ='Quality Assurance').first() is not None):
                    q_group = True
                    role_name ="Quality Assurance"            

                if (request.user.groups.filter(name ='Developer').first() is not None):
                    d_group = True
                    role_name ="Developer"

                if (request.user.groups.filter(name ='Admin').first() is not None):
                    a_group = True

                if (request.user.groups.filter(name ='Owner').first() is not None):
                    o_group = True

                if obj.goal_status == forms:
                    return HttpResponse("you cannot move your current goal back to to the same status")

                if d_group:
                    if forms == doneGoalStatus:
                        return HttpResponse("A user with '"+role_name+"'group cannot move goal to done")
                    if obj.user != request.user :
                        return HttpResponse("A user with '"+role_name+"' can only move self created goals")

                if q_group:
                    # if obj.user == request.user :
                    #     if forms == weeklyGoalStatus:
                    #         return HttpResponse("A user with '"+role_name+"' group can not move self created goal to weekly goal")
                    if obj.user != request.user :
                        if forms != doneGoalStatus:
                            return HttpResponse("A user with '"+role_name+"' group can only move other user goal to done goal")

                obj.goal_status = forms
                obj.save()
                return HttpResponse("Goal was moved successfully")
                # return redirect("dotman007_richardscrumy:home")

                
        else:
            form = MoveGoalForm()
            return render(request, 'dotman007_richardscrumy/move_goal.html', context={"move": form})



@login_required(login_url='dotman007_richardscrumy:login_page')
def add_goal(request):
    if request.method == 'POST':
        goal = CreateGoalForm(request.POST)
        d_group = False
        q_group = False
        a_group = False
        o_group = False
        role_name =""        

        if goal.is_valid():
            myGoalStatus = GoalStatus.objects.get(status_name = 'Weekly Goal')
            weeklyGoalStatus = GoalStatus.objects.get(status_name = 'Weekly Goal')
            myGoalUser = User.objects.get(username = request.user.username)
                       
            if (request.user.groups.filter(name ='Quality Assurance').first() is not None):
                q_group = True
                role_name ="Quality Assurance"            

            if (request.user.groups.filter(name ='Developer').first() is not None):
                d_group = True
                role_name ="Developer"

            if (request.user.groups.filter(name ='Admin').first() is not None):
                a_group = True

            if (request.user.groups.filter(name ='Owner').first() is not None):
                o_group = True
           
            if (((d_group or q_group ) and myGoalStatus == weeklyGoalStatus and request.user.username == myGoalUser.username) or (a_group or o_group)):
                ScrumyGoals.objects.create(
                    user=User.objects.get(username=request.user.username),
                    goal_name=goal.cleaned_data['goal_name'],
                    goal_id= random.randint(1000,9999),
                    created_by = 'Louis',
                    moved_by='Louis',
                    owner='Louis',
                    goal_status=GoalStatus.objects.get(status_name='Weekly Goal') 
                )
            elif ((d_group or q_group ) and myGoalStatus != weeklyGoalStatus and request.user.username == myGoalUser.username):               
                return HttpResponse("A user with '"+role_name+"' group can only create weekly goal")           

            elif ((d_group or q_group ) and request.user.username != myGoalUser.username):
                return HttpResponse("A user with '"+role_name+"' group can only create goal for self")
            
            return HttpResponse("Goal Added successfully")
            
        else:
            return redirect("dotman007_richardscrumy:add_goal")
    
    else:
        goal = CreateGoalForm()
        return render(request, 'dotman007_richardscrumy/add_goal.html', context={"goal": goal})


@login_required(login_url='dotman007_richardscrumy:login_page')
def home(request):
    users = User.objects.all()
    daily_set=GoalStatus.objects.get(status_name='Daily Goal').scrumygoals_set.all()
    weekly_set=GoalStatus.objects.get(status_name='Weekly Goal').scrumygoals_set.all()
    verify_set=GoalStatus.objects.get(status_name='Verify Goal').scrumygoals_set.all()
    done_set=GoalStatus.objects.get(status_name='Done Goal').scrumygoals_set.all()
    d_group= False
    goal = CreateGoalForm()
    

    if (request.user.groups.filter(name ='Developer').first() is not None):
        d_group = True

    form = MoveGoalForm()  
    
    context= {'users':users, 'daily' : daily_set, 'weekly': weekly_set, 'verify': verify_set, 'done': done_set ,'d_group':d_group,'move':form,'groupList':Group.objects.all(), 'goal':goal}

    return render(request, 'dotman007_richardscrumy/home.html', context)

@login_required(login_url='dotman007_richardscrumy:login_page')
def change_group(request):
    if request.method == 'POST':
        groups = GroupChange(request.POST)        
        if groups.is_valid():
            my_group= Group.objects.get(name=groups.cleaned_data['group_name'])
            user = User.objects.get(username=request.user.username)
            user.groups.clear()
            my_group.user_set.add(user)
            my_group.save()
            return HttpResponse('role changed successfully')
        else:
            groups = GroupChange()
            context={
                'groupList':Group.objects.all(),
                'group':groups
            }            
            return render(request, 'dotman007_richardscrumy/group_name.html', context)
    else:
        groups = GroupChange()
        context={
                'groupList':Group.objects.all(),
                'group':groups
            }       
        

dotman007_richardscrumy/templates/dotman007_richardscrumy/add_goal.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

<nav style="float: right; padding: 20px; background-color:blanchedalmond;">
    <span style="padding: 20px; font-size:large"> <strong>Hello, {{request.user}}</strong></span>

    {% if request.user.is_authenticated %}
        <span style="font-size:large"> <strong>Group:</strong> 
            {% for group in request.user.groups.all %}
            {{ group }}{% endfor %}
        </span>
    {% endif %}
</nav><br>


    <form action="{%  url 'dotman007_richardscrumy:add_goal'%}" method="post">
        {%csrf_token%}
        {{ goal }}

        <input type="submit" value="Submit">
    </form>
</body>
</html>

dotman007_richardscrumy/templates/dotman007_richardscrumy/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta name="description" content="" />
    <meta name="author" content="" />

    <title>Goals Management</title>

    <!-- Custom fonts for this template-->
    <link
      href="{% static 'vendor/fontawesome-free/css/all.min.css' %}"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
      rel="stylesheet"
    />

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet" />

    <link href="{% static 'vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
  </head>

  <body id="page-top">
    <!-- Page Wrapper -->
    <div id="wrapper">
      <!-- Sidebar -->
      <ul
        class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion"
        id="accordionSidebar"
      >
        <!-- Sidebar - Brand -->
        <a
          class="sidebar-brand d-flex align-items-center justify-content-center"
          href="index.html"
        >
          <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-laugh-wink"></i>
          </div>
          <div class="sidebar-brand-text mx-3">Goals <sup>Management</sup></div>
        </a>

        <!-- Divider -->
        <hr class="sidebar-divider my-0" />

        <!-- Nav Item - Dashboard -->
        <li class="nav-item">
          <a class="nav-link" href="{% url 'dotman007_richardscrumy:home'%}">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Home</span></a
          >
        </li>

     
        <!-- Nav Item - Pages Collapse Menu -->
        <li class="nav-item">
          <a
            class="nav-link collapsed"
            href="#"
            data-toggle="collapse"
            data-target="#collapseTwo"
            aria-expanded="true"
            aria-controls="collapseTwo"
          >
            <i class="fas fa-fw fa-cog"></i>
            <span>Group</span>
          </a>
          <div
            id="collapseTwo"
            class="collapse"
            aria-labelledby="headingTwo"
            data-parent="#accordionSidebar"
          >
            <div class="bg-white py-2 collapse-inner rounded">
              <h6 class="collapse-header">Current User Group:</h6>
              <a class="collapse-item" href="{% url 'dotman007_richardscrumy:group'%}" data-toggle="modal"  data-target="#changGroupModal">Change Group</a>
              <a class="collapse-item" href="#">Add new Group</a>
            </div>
          </div>
        </li>

      
        

        <!-- Nav Item - Charts -->
        <li class="nav-item">
          <a class="nav-link" href="{% url 'dotman007_richardscrumy:logout_page'%}">
            <i class="fas fa-fw fa-chart-area"></i>
            <span>Logout</span></a
          >
        </li>

       
        <!-- Divider -->
        <hr class="sidebar-divider d-none d-md-block" />

        <!-- Sidebar Toggler (Sidebar) -->
        <div class="text-center d-none d-md-inline">
          <button class="rounded-circle border-0" id="sidebarToggle"></button>
        </div>
      </ul>
      <!-- End of Sidebar -->

      <!-- Content Wrapper -->
      <div id="content-wrapper" class="d-flex flex-column">
        <!-- Main Content -->
        <div id="content">
          <!-- Topbar -->
          <nav
            class="
              navbar navbar-expand navbar-light
              bg-white
              topbar
              mb-4
              static-top
              shadow
            "
          >
            <!-- Sidebar Toggle (Topbar) -->
            <button
              id="sidebarToggleTop"
              class="btn btn-link d-md-none rounded-circle mr-3"
            >
              <i class="fa fa-bars"></i>
            </button>

           

<div  class="">
<span style="padding: 20px; font-size:large"> <strong>Hello, {{request.user}}</strong></span>
      
{% if request.user.is_authenticated %}
    <span style="font-size:large"> <strong>Group:</strong> 
        {% for group in request.user.groups.all %}
        {{ group }}{% endfor %}
    </span>
{% endif %}

<a href="{% url 'dotman007_richardscrumy:group'%}" class="btn btn-primary btn-icon-split"
 data-toggle="modal"  data-target="#changGroupModal"
>
  <span class="icon text-white-50">
      <i class="fas fa-flag"></i>
  </span>
  <span class="text">Change Group</span>
</a>

  <!-- <button class="btn btn-success btn-sm"><a href="{% url 'dotman007_richardscrumy:group'%}"> Change Group</a></button> 
  <button class="btn btn-danger btn-sm"><a href="{% url 'dotman007_richardscrumy:logout_page'%}"> Logout</a></button>  -->


</div>
           
         




            <!-- Topbar Navbar -->
            <ul class="navbar-nav ml-auto">
              <!-- Nav Item - Search Dropdown (Visible Only XS) -->
              <li class="nav-item dropdown no-arrow d-sm-none">
                <a
                  class="nav-link dropdown-toggle"
                  href="#"
                  id="searchDropdown"
                  role="button"
                  data-toggle="dropdown"
                  aria-haspopup="true"
                  aria-expanded="false"
                >
                  <i class="fas fa-search fa-fw"></i>
                </a>
                <!-- Dropdown - Messages -->
                <div
                  class="
                    dropdown-menu dropdown-menu-right
                    p-3
                    shadow
                    animated--grow-in
                  "
                  aria-labelledby="searchDropdown"
                >
                  <form class="form-inline mr-auto w-100 navbar-search">
                    <div class="input-group">
                      <input
                        type="text"
                        class="form-control bg-light border-0 small"
                        placeholder="Search for..."
                        aria-label="Search"
                        aria-describedby="basic-addon2"
                      />
                      <div class="input-group-append">
                        <button class="btn btn-primary" type="button">
                          <i class="fas fa-search fa-sm"></i>
                        </button>
                      </div>
                    </div>
                  </form>
                </div>
              </li>

              <!-- Nav Item - Alerts -->
              <li class="nav-item dropdown no-arrow mx-1">
                <a href="{% url 'dotman007_richardscrumy:logout_page'%}" style="margin-top: 15px;" class="btn btn-danger btn-icon-split">
                  <span class="icon text-white-50">
                      <i class="fas fa-sign-out-alt"></i>
                  </span>
                  <span class="text">Sign Out</span>
                </a>
              </li>

            

              <div class="topbar-divider d-none d-sm-block"></div>

              <!-- Nav Item - User Information -->
              <li class="nav-item dropdown no-arrow">
                <a
                  class="nav-link dropdown-toggle"
                  href="#"
                  id="userDropdown"
                  role="button"
                  data-toggle="dropdown"
                  aria-haspopup="true"
                  aria-expanded="false"
                >
                  <span class="mr-2 d-none d-lg-inline text-gray-600 small"
                    >{{request.user}}</span
                  >
                  <img
                    class="img-profile rounded-circle"
                    src="{% static 'img/undraw_profile.svg' %}"
                  />
                </a>
                <!-- Dropdown - User Information -->
                <div
                  class="
                    dropdown-menu dropdown-menu-right
                    shadow
                    animated--grow-in
                  "
                  aria-labelledby="userDropdown"
                >
                
                  <a class="dropdown-item" href="{% url 'dotman007_richardscrumy:group'%}" data-toggle="modal"  data-target="#changGroupModal">
                    <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                    Change Group
                  </a>
                  <a class="dropdown-item" href="{%  url 'dotman007_richardscrumy:add_goal'%}" data-toggle="modal"  data-target="#addGoalModal">
                    <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                    Add Goal
                  </a>
                  <div class="dropdown-divider"></div>
                  <a
                    class="dropdown-item"
                    href="{% url 'dotman007_richardscrumy:logout_page'%}"
                    data-toggle="modal"
                    data-target="#logoutModal"
                  >
                    <i
                      class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"
                    ></i>
                    Logout
                  </a>
                </div>
              </li>
            </ul>
          </nav>
          <!-- End of Topbar -->

          <!-- Begin Page Content -->
          <div class="container-fluid">
            <h1 class="h3 mb-4 text-gray-800">
              {% block title %}{% endblock title %}
            </h1>
            {% block content %}{% endblock content %}

            <!-- Page Heading -->
          </div>
          <!-- /.container-fluid -->
        </div>
        <!-- End of Main Content -->

        <!-- Footer -->
        <footer class="sticky-footer bg-white">
          <div class="container my-auto">
            <div class="copyright text-center my-auto">
              <span>Copyright &copy; linuxjobber.com 2021</span>
            </div>
          </div>
        </footer>
        <!-- End of Footer -->
      </div>
      <!-- End of Content Wrapper -->
    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
      <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div
      class="modal fade"
      id="logoutModal"
      tabindex="-1"
      role="dialog"
      aria-labelledby="exampleModalLabel"
      aria-hidden="true"
    >
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
            <button
              class="close"
              type="button"
              data-dismiss="modal"
              aria-label="Close"
            >
              <span aria-hidden="true">×</span>
            </button>
          </div>
          <div class="modal-body">
            Select "Logout" below if you are ready to end your current session.
          </div>
          <div class="modal-footer">
            <button
              class="btn btn-secondary"
              type="button"
              data-dismiss="modal"
            >
              Cancel
            </button>
            <a class="btn btn-primary" href="{% url 'dotman007_richardscrumy:logout_page'%}">Logout</a>
          </div>
        </div>
      </div>
    </div>



    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

        <!-- Page level plugins -->
    <script src="{% static 'vendor/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'js/demo/datatables-demo.js' %}"></script>
  </body>
</html>

dotman007_richardscrumy/templates/dotman007_richardscrumy/exception.html
<p>{{ error }}</p>

dotman007_richardscrumy/templates/dotman007_richardscrumy/login_page.html
<!DOCTYPE html>
<html>
    
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
			
		}

		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
                    {% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

				</div>
				{% for message in messages  %}
					<p>{{message}}</p>
				{% endfor %}
                    
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'dotman007_richardscrumy:about' %}" class="ml-2">Sign Up</a>
					</div>
			
				</div>
			</div>
		</div>
	</div>
</body>

</html>